<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Category;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Storage;

class CategorySeeder extends Seeder
{
    public function run(): void
    {
        $placeholderPath = 'uploads/categories/placeholder.png';

        if (!Storage::disk('public')->exists($placeholderPath)) {
            $base64 = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y2Gj54AAAAASUVORK5CYII=';
            Storage::disk('public')->put($placeholderPath, base64_decode($base64));
        }

        $categories = [];

        for ($i = 1; $i <= 10; $i++) {
            $title = "Category {$i}";

            $categories[] = [
                'id'             => Str::uuid(),
                'parent_id'      => null,
                'title'          => $title,
                'slug' => Str::slug($title) . '-' . Str::random(5),
                'image'          => $placeholderPath,
                'sort_order'     => $i,

                'content'        => "This is sample content for {$title}. Generated by CategorySeeder for testing.",

                'meta_title'     => "{$title} - Meta Title",
                'meta_keywords'  => "sample, {$title}, category, ecommerce, demo",
                'meta_desc'      => "This is a meta description for {$title}, generated for seeding purposes.",

                'publish_status' => rand(0, 1),

                'created_at'     => now(),
                'updated_at'     => now(),
            ];
        }

        Category::insert($categories);
    }
}
